# Generated by Django 5.2.8 on 2026-01-08 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_confirmed', 'การจองได้รับการยืนยัน'), ('booking_in_progress', 'เริ่มดำเนินการซ่อม'), ('booking_completed', 'งานเสร็จสิ้น'), ('booking_cancelled', 'การจองถูกยกเลิก'), ('booking_rejected', 'ช่างปฏิเสธงาน'), ('mechanic_assigned', 'มีช่างรับงาน')], max_length=50, verbose_name='ประเภทการแจ้งเตือน')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('message', models.TextField(verbose_name='ข้อความ')),
                ('is_read', models.BooleanField(default=False, verbose_name='อ่านแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='booking.booking', verbose_name='การจอง')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'verbose_name_plural': 'การแจ้งเตือนทั้งหมด',
                'ordering': ['-created_at'],
            },
        ),
    ]
