# Generated by Django 5.2.8 on 2026-01-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'การจองได้รับการยืนยัน'), ('booking_in_progress', 'เริ่มดำเนินการซ่อม'), ('booking_completed', 'งานเสร็จสิ้น'), ('booking_cancelled', 'การจองถูกยกเลิก'), ('booking_rejected', 'ช่างปฏิเสธงาน'), ('mechanic_assigned', 'มีช่างรับงาน'), ('new_work_assigned', 'มีงานใหม่เข้ามา'), ('new_booking_available', 'มีงานใหม่รอรับ'), ('work_taken_by_other', 'มีช่างอื่นรับงานแล้ว'), ('work_cancelled_by_customer', 'ลูกค้ายกเลิกงาน')], max_length=50, verbose_name='ประเภทการแจ้งเตือน'),
        ),
    ]
