# Generated by Django 6.0 on 2025-12-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'ผู้ใช้'), ('bot', 'บอท')], max_length=10, verbose_name='ผู้ส่ง')),
                ('message', models.TextField(verbose_name='ข้อความ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลา')),
                ('n8n_response', models.JSONField(blank=True, null=True, verbose_name='ข้อมูลจาก n8n')),
            ],
            options={
                'verbose_name': 'ข้อความแชท',
                'verbose_name_plural': 'ข้อความแชททั้งหมด',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='รหัสเซสชัน')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='เริ่มเมื่อ')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='สิ้นสุดเมื่อ')),
                ('is_active', models.BooleanField(default=True, verbose_name='กำลังใช้งาน')),
            ],
            options={
                'verbose_name': 'เซสชันแชท',
                'verbose_name_plural': 'เซสชันแชททั้งหมด',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MotorcycleKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='ยี่ห้อ')),
                ('model', models.CharField(max_length=100, verbose_name='รุ่น')),
                ('problem_category', models.CharField(max_length=100, verbose_name='ประเภทปัญหา')),
                ('symptom', models.TextField(verbose_name='อาการ')),
                ('solution', models.TextField(verbose_name='วิธีแก้ไข')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='แหล่งที่มา')),
                ('scraped_data', models.JSONField(blank=True, null=True, verbose_name='ข้อมูลที่ดึงมา')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่ม')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
            ],
            options={
                'verbose_name': 'ความรู้เกี่ยวกับรถ',
                'verbose_name_plural': 'ความรู้เกี่ยวกับรถทั้งหมด',
                'ordering': ['-created_at'],
            },
        ),
    ]
