# Generated by Django 5.2.8 on 2025-12-20 14:06

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycleknowledge',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='Vector Embedding'),
        ),
    ]
