# Generated by Django 5.2.8 on 2026-01-02 05:55

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_motorcycleknowledge_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledgebase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='หัวข้อ')),
                ('content', models.TextField(verbose_name='เนื้อหา')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='หมวดหมู่')),
                ('source', models.CharField(default='pantip', max_length=50, verbose_name='แหล่งที่มา')),
                ('source_url', models.URLField(unique=True, verbose_name='URL แหล่งที่มา')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='ผู้เขียน')),
                ('views', models.IntegerField(default=0, verbose_name='ยอดเข้าชม')),
                ('replies', models.IntegerField(default=0, verbose_name='ยอดตอบกลับ')),
                ('likes', models.IntegerField(default=0, verbose_name='ยอดไลค์')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='แท็ก')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='ข้อมูลดิบ')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='Vector Embedding')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='เผยแพร่เมื่อ')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='สกัดข้อมูลเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัพเดทล่าสุด')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('is_verified', models.BooleanField(default=False, verbose_name='ตรวจสอบแล้ว')),
            ],
            options={
                'verbose_name': 'ฐานความรู้',
                'verbose_name_plural': 'ฐานความรู้ทั้งหมด',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['source', 'category'], name='chatbot_kno_source_6ca249_idx'), models.Index(fields=['is_active', 'is_verified'], name='chatbot_kno_is_acti_fdcc39_idx'), models.Index(fields=['-published_at'], name='chatbot_kno_publish_eee771_idx')],
            },
        ),
    ]
