# Generated by Django 5.2.8 on 2026-01-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_knowledgebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='pantip หรือ honda', max_length=50, verbose_name='แหล่งที่มา')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='URL แหล่งที่มา')),
                ('title', models.CharField(max_length=500, verbose_name='หัวข้อ/ชื่อรุ่น')),
                ('content', models.TextField(verbose_name='เนื้อหา/รายละเอียด')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='หมวดหมู่')),
                ('raw_data', models.JSONField(help_text='เก็บข้อมูลทั้งหมดจาก source', verbose_name='ข้อมูลดิบ JSON')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='ผู้เขียน')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='ยี่ห้อ')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='รุ่น')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='ราคา')),
                ('views', models.IntegerField(default=0, verbose_name='ยอดเข้าชม')),
                ('comments_count', models.IntegerField(default=0, verbose_name='จำนวนคอมเมนต์')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='เผยแพร่เมื่อ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัพเดทล่าสุด')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
            ],
            options={
                'verbose_name': 'ฐานความรู้',
                'verbose_name_plural': 'ฐานความรู้ทั้งหมด',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Knowledgebase',
        ),
        migrations.DeleteModel(
            name='MotorcycleKnowledge',
        ),
        migrations.AddIndex(
            model_name='knowledgedatabase',
            index=models.Index(fields=['source', 'category'], name='chatbot_kno_source_142d65_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedatabase',
            index=models.Index(fields=['brand', 'model'], name='chatbot_kno_brand_44daa4_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedatabase',
            index=models.Index(fields=['is_active'], name='chatbot_kno_is_acti_c2a3a8_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedatabase',
            index=models.Index(fields=['-published_at'], name='chatbot_kno_publish_4b8b5a_idx'),
        ),
    ]
