# Generated by Django 5.2.8 on 2026-01-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_knowledgedatabase_delete_knowledgebase_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnowledgeDatabase',
            new_name='KnowlageDatabase',
        ),
        migrations.RenameIndex(
            model_name='knowlagedatabase',
            new_name='DatabaseKno_source_4ef337_idx',
            old_name='chatbot_kno_source_142d65_idx',
        ),
        migrations.RenameIndex(
            model_name='knowlagedatabase',
            new_name='DatabaseKno_brand_46c3c4_idx',
            old_name='chatbot_kno_brand_44daa4_idx',
        ),
        migrations.RenameIndex(
            model_name='knowlagedatabase',
            new_name='DatabaseKno_is_acti_32b1b1_idx',
            old_name='chatbot_kno_is_acti_c2a3a8_idx',
        ),
        migrations.RenameIndex(
            model_name='knowlagedatabase',
            new_name='DatabaseKno_publish_b17fc3_idx',
            old_name='chatbot_kno_publish_4b8b5a_idx',
        ),
        migrations.AlterModelTable(
            name='knowlagedatabase',
            table='DatabaseKnowlage',
        ),
    ]
