# Generated by Django 5.2.8 on 2026-01-05 04:24

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_rename_knowledgedatabase_knowlagedatabase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowlagedatabase',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True, verbose_name='Vector Embedding'),
        ),
    ]
