# Generated by Django 5.2.8 on 2026-01-05 07:12

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_knowlagedatabase_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowlagedatabase',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='Vector Embedding'),
        ),
    ]
