# Generated by Django 5.2.8 on 2026-01-05 18:56

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_alter_knowlagedatabase_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('source', models.CharField(db_index=True, default='honda', max_length=100)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Knowledge Base',
                'verbose_name_plural': 'Knowledge Base',
                'db_table': 'KnowBase',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'brand'], name='KnowBase_source_da5da4_idx'), models.Index(fields=['brand', 'model'], name='KnowBase_brand_af6223_idx')],
            },
        ),
    ]
