# Generated by Django 5.2.8 on 2026-01-05 20:53

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_knowbase'),
    ]

    operations = [
        migrations.RunSQL(
            sql='UPDATE "KnowBase" SET embedding = NULL',
            reverse_sql="SELECT 1",
        ),
        migrations.AlterField(
            model_name='knowbase',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
