# Generated by Django 5.2.8 on 2026-01-06 12:29

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_alter_knowbase_embedding'),
    ]

    operations = [
        migrations.RunSQL(
            sql='UPDATE "knowbase" SET embedding = NULL',
            reverse_sql="SELECT 1",
        ),
        migrations.AlterField(
            model_name='knowbase',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
