# Generated by Django 5.2.8 on 2026-01-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_alter_knowbase_embedding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knowbase',
            new_name='knowbase_source_eae662_idx',
            old_name='knowbase_source_da5da4_idx',
        ),
        migrations.RenameIndex(
            model_name='knowbase',
            new_name='knowbase_brand_50527c_idx',
            old_name='knowbase_brand_af6223_idx',
        ),
    ]
