# Generated by Django 5.2.8 on 2026-02-20 15:07

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_change_embedding_768_to_3072_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowbase',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
        migrations.AlterField(
            model_name='knowlagedatabase',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True, verbose_name='Vector Embedding'),
        ),
    ]
