# Generated by Django 6.0.1 on 2026-03-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_change_knowlagedatabase_embedding_768_to_3072'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowbaseEmbedQueue',
            fields=[
            ],
            options={
                'verbose_name': 'คิว Embedding (รอดำเนินการ)',
                'verbose_name_plural': 'จัดการ Embedding (รอดำเนินการ)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chatbot.knowbase',),
        ),
        migrations.AlterModelOptions(
            name='knowbase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Knowbase', 'verbose_name_plural': 'Knowbases'},
        ),
    ]
