# Generated by Django 6.0.1 on 2026-03-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_knowbaseembedqueue_alter_knowbase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at'], 'verbose_name': 'เซสชันแชท', 'verbose_name_plural': 'เซสชันแชททั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='knowbaseembedqueue',
            options={'verbose_name': 'Embedding (รอดำเนินการ)', 'verbose_name_plural': 'Embedding '},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ชื่อบทสนทนา'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด'),
        ),
        migrations.AlterField(
            model_name='knowbase',
            name='source',
            field=models.CharField(db_index=True, default='Brand', max_length=100),
        ),
    ]
