# Generated by Django 5.2.8 on 2026-04-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_alter_chatsession_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='knowbase',
            name='knowbase_source_eae662_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowbase',
            name='knowbase_brand_50527c_idx',
        ),
        migrations.RemoveField(
            model_name='knowbase',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='knowbase',
            name='model',
        ),
        migrations.RemoveField(
            model_name='knowbase',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='knowbase',
            name='source',
        ),
    ]
