# Generated by Django 5.2.8 on 2026-01-09 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='booking.booking', verbose_name='การจอง')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_chats', to=settings.AUTH_USER_MODEL, verbose_name='ลูกค้า')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_chats', to=settings.AUTH_USER_MODEL, verbose_name='ช่าง')),
            ],
            options={
                'verbose_name': 'ห้องแชท',
                'verbose_name_plural': 'ห้องแชททั้งหมด',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='ข้อความ')),
                ('is_read', models.BooleanField(default=False, verbose_name='อ่านแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ส่ง')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='ห้องแชท')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ส่ง')),
            ],
            options={
                'verbose_name': 'ข้อความ',
                'verbose_name_plural': 'ข้อความทั้งหมด',
                'ordering': ['created_at'],
            },
        ),
    ]
