# Generated by Django 6.0 on 2025-12-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField(verbose_name='อาการที่พบ')),
                ('appointment_date', models.DateTimeField(verbose_name='วันเวลานัด')),
                ('status', models.CharField(choices=[('pending', 'รอยืนยัน'), ('confirmed', 'ยืนยันแล้ว'), ('in_progress', 'กำลังซ่อม'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาโดยประมาณ')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาจริง')),
                ('repair_notes', models.TextField(blank=True, null=True, verbose_name='รายละเอียดการซ่อม')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่เสร็จสิ้น')),
                ('pickup_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่นัดรับรถ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่จอง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
            ],
            options={
                'verbose_name': 'การจองคิว',
                'verbose_name_plural': 'การจองคิวทั้งหมด',
                'ordering': ['-appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='ยี่ห้อ')),
                ('model', models.CharField(max_length=100, verbose_name='รุ่น')),
                ('year', models.IntegerField(verbose_name='ปี')),
                ('cc', models.IntegerField(verbose_name='ความจุกระบอกสูบ (cc)')),
                ('bike_type', models.CharField(choices=[('standard', 'รถมาตรฐาน 150cc'), ('sport', 'รถสปอร์ต'), ('cruiser', 'รถครูเซอร์'), ('touring', 'รถทัวร์ริ่ง'), ('adventure', 'รถแอดเวนเจอร์'), ('superbike', 'ซุปเปอร์ไบค์'), ('other', 'อื่นๆ')], default='standard', max_length=20, verbose_name='ประเภทรถ')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='ทะเบียนรถ')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='สี')),
                ('mileage', models.IntegerField(default=0, verbose_name='เลขไมล์')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่ม')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
            ],
            options={
                'verbose_name': 'รถจักรยานยนต์',
                'verbose_name_plural': 'รถจักรยานยนต์ทั้งหมด',
                'ordering': ['-created_at'],
            },
        ),
    ]
