# Generated by Django 6.0 on 2025-12-14 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='ลูกค้า'),
        ),
        migrations.AddField(
            model_name='booking',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanic_bookings', to=settings.AUTH_USER_MODEL, verbose_name='ช่างที่รับผิดชอบ'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorcycles', to=settings.AUTH_USER_MODEL, verbose_name='เจ้าของ'),
        ),
        migrations.AddField(
            model_name='booking',
            name='motorcycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.motorcycle', verbose_name='รถจักรยานยนต์'),
        ),
    ]
