# Generated by Django 5.2.8 on 2026-02-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='actual_cost',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='mileage',
        ),
    ]
