# Generated by Django 5.2.8 on 2026-02-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_actual_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ค่าประเมินการซ่อม'),
        ),
    ]
