# Generated by Django 5.2.8 on 2026-02-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_estimated_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ค่าซ่อมจริง'),
        ),
        migrations.AddField(
            model_name='booking',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่ซ่อมเสร็จ'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่รับรถ'),
        ),
    ]
