# Generated by Django 5.2.8 on 2026-02-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_actual_cost_booking_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='สี'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์ (กม.)'),
        ),
    ]
