# Generated by Django 6.0.1 on 2026-03-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_motorcycle_color_motorcycle_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='bike_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('sport', 'Sport'), ('touring', 'Touring'), ('adventure', 'Adventure'), ('super_sport', 'Super Sport'), ('sport_touring', 'Sport Touring'), ('custom_bobber', 'Custom Bobber'), ('race', 'Race (Track only)')], default='classic', max_length=20, verbose_name='ประเภทรถ'),
        ),
    ]
