# Generated by Django 6.0.1 on 2026-03-05 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_motorcycle_bike_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='bike_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('standard', 'Standard'), ('sport', 'Sport'), ('touring', 'Touring'), ('adventure', 'Adventure'), ('super_sport', 'Super Sport'), ('sport_touring', 'Sport Touring'), ('custom_bobber', 'Custom Bobber'), ('race', 'Race (Track only)')], default='classic', max_length=20, verbose_name='ประเภทรถ'),
        ),
        migrations.CreateModel(
            name='BookingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='booking_images/', verbose_name='รูปภาพ')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='คำอธิบายรูป')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='อัปโหลดเมื่อ')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking.booking', verbose_name='การจอง')),
            ],
            options={
                'verbose_name': 'รูปภาพการจอง',
                'verbose_name_plural': 'รูปภาพการจองทั้งหมด',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
