# Generated by Django 6.0 on 2025-12-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('engine', 'เครื่องยนต์'), ('electrical', 'ระบบไฟฟ้า'), ('brake', 'ระบบเบรก'), ('suspension', 'ระบบกันสะเทือน'), ('transmission', 'ระบบส่งกำลัง'), ('body', 'โครงสร้างและตัวถัง'), ('all', 'ซ่อมทั่วไป')], default='all', max_length=20, verbose_name='ความเชี่ยวชาญ')),
                ('years_of_experience', models.IntegerField(default=0, verbose_name='ประสบการณ์ (ปี)')),
                ('certification', models.CharField(blank=True, max_length=200, null=True, verbose_name='ใบรับรอง')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='ประวัติ')),
                ('is_available', models.BooleanField(default=True, verbose_name='พร้อมรับงาน')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='คะแนนเฉลี่ย')),
                ('total_jobs', models.IntegerField(default=0, verbose_name='งานทั้งหมด')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
            ],
            options={
                'verbose_name': 'โปรไฟล์ช่าง',
                'verbose_name_plural': 'โปรไฟล์ช่างทั้งหมด',
                'ordering': ['-rating', '-total_jobs'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='คะแนน')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='ความคิดเห็น')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่รีวิว')),
            ],
            options={
                'verbose_name': 'รีวิว',
                'verbose_name_plural': 'รีวิวทั้งหมด',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'รอรับงาน'), ('accepted', 'รับงานแล้ว'), ('rejected', 'ปฏิเสธงาน')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='มอบหมายเมื่อ')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='ตอบรับเมื่อ')),
            ],
            options={
                'verbose_name': 'คิวงาน',
                'verbose_name_plural': 'คิวงานทั้งหมด',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
