# Generated by Django 6.0 on 2025-12-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workqueue',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เสร็จสิ้นเมื่อ'),
        ),
        migrations.AddField(
            model_name='workqueue',
            name='priority',
            field=models.CharField(choices=[('low', 'ต่ำ'), ('medium', 'ปานกลาง'), ('high', 'สูง'), ('urgent', 'ด่วน')], default='medium', max_length=20, verbose_name='ความสำคัญ'),
        ),
        migrations.AddField(
            model_name='workqueue',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เริ่มงานเมื่อ'),
        ),
        migrations.AlterField(
            model_name='workqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'รอรับงาน'), ('accepted', 'รับงานแล้ว'), ('in_progress', 'กำลังซ่อม'), ('completed', 'เสร็จสิ้น'), ('rejected', 'ปฏิเสธงาน')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
    ]
