# Generated by Django 5.2.8 on 2026-01-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0003_workqueue_completed_at_workqueue_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='mechanic_licenses/', verbose_name='ใบอนุญาตประกอบการ'),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='วุฒิการศึกษา'),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='qualification_file',
            field=models.FileField(blank=True, null=True, upload_to='mechanic_qualifications/', verbose_name='ไฟล์วุฒิการศึกษา'),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='shop_address',
            field=models.TextField(blank=True, null=True, verbose_name='ที่อยู่ร้าน'),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='shop_photo',
            field=models.ImageField(blank=True, null=True, upload_to='mechanic_shops/', verbose_name='รูปหน้าร้าน'),
        ),
    ]
