# Generated by Django 5.2.8 on 2026-02-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0004_mechanicprofile_license_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
